### ISSUE TITLE
A axis <360

### ISSUE THREAD

**Issue by wwwlxs** [svenhb/GRBL-Plotter#116]
Hi svenHB，Can you add the following function to the new version of grblplotter: If the angle change is greater than 360 degrees, the z axis will move up, the axis will rotate -360 degrees, and then move down to return to the original angle, for example, when the A axis is 361, will  Return 1 degree. This function can prevent the dispenser's trachea from rotating too many times and causing a break ,i have leave a message to your instagram.Best wishes !

![4A3E727A-ADDA-43E5-8C49-B318FC661977](https://user-images.githubusercontent.com/44305220/79046397-504b8100-7c43-11ea-84e9-b56ca7acfe0c.jpeg)

![FE7B7398-82E5-4BF7-9740-5DE93EC2D7F0](https://user-images.githubusercontent.com/44305220/79046581-6279ef00-7c44-11ea-9934-792dd1e6a2e0.jpeg)

**Comment by svenhb** [comment]
I see.
How to handle an exceed of 360° during a move? Interrupt or finish the move, then 'unwrap'?

**Comment by wwwlxs** [comment]
Interrupt. turn back to the same angle (for example, if -361degrees, then +360, turn to -1degrees, if 361degrees , then -360, turn to 1degrees, that is, the rotation is controlled within + -360 degrees,) avoid too much rotation too many turns, after completing the angle rotation, continue to move forward

**Comment by lianzaozi** [comment]
You said that this function is very good, I think when the rotation angle is greater than 360, it is a good idea whether the Z axis rises and turns. This function should be made into an option for users to choose. Because some users have pneumatic slip rings installed on their machines, the pneumatic slip rings can prevent the trachea from being entangled when the shaft rotates more than 360 °. Such users do not need to turn on the function of Z-axis rising and turning when it is greater than 360 °.

**Comment by svenhb** [comment]
I built in such option, hope it works as expected
https://github.com/svenhb/GRBL-Plotter/releases

**Comment by wwwlxs** [comment]
thanks
