### ISSUE TITLE
Rotation Gcode arround camera cross center

### ISSUE THREAD

**Issue by alligator77** [svenhb/GRBL-Plotter#177]
Can add feature to rotate GCode arround camera cross center without activate "Auto alignment"? Tnx

![изображение](https://user-images.githubusercontent.com/6526798/105092690-9e36c480-5ab2-11eb-9deb-42077d197c14.png)

**Comment by svenhb** [comment]
Yes should be possible

**Comment by alligator77** [comment]
> 
> 
> Yes should be possible

Tnx.

One more question. Are you planning to implement 3D previews?

**Comment by svenhb** [comment]
Sorry, no 3D view in planning.

**Comment by svenhb** [comment]
Try https://github.com/svenhb/GRBL-Plotter/releases

**Comment by alligator77** [comment]
Sorry, a little bit wrong, has need to turn not from 0: 0, but from the center of the yellow cross, and it can be anywhere.

![изображение](https://user-images.githubusercontent.com/6526798/105537257-b43ac400-5d02-11eb-8d31-c22be47481db.png)

**Comment by svenhb** [comment]
I would follow this description: https://github.com/svenhb/GRBL-Plotter/wiki/PCB-drilling
It should work like this...
0) reset offet (right click in camera view G92.1)
1) Switch to 'Cam coord.'
2) select marker = center of rotation in 2D-view in main GUI
3) move camera view to same position on real object
4) In camera view, right click on  select 'Set actual pos. to marker pos.'
5) in 2D view select next marker as reference for rotation and scale
6) move camera view to same position on real object
7) In camera view, right click on  select 'Compensate angle and scale'

**Comment by alligator77** [comment]
Ok, I check this out

**Comment by engrjawadulhassan** [comment]
Hello,
I hope every one doing great.

I am having issues , with orientation of G code for drilling an etched PCB. 
I was using the latest version of GRBL plotter for this task, but when i reached the tutorial , the tutorial was for a previous version the software. Than , i downloaded the previous version 1.5.2 , it give me access to same camera window with tool cord and cam cord selection, I have followed the whole tutorial and steps as described.
https://github.com/svenhb/GRBL-Plotter/wiki/PCB-drilling

But still i am having an error while performing the drill JOB , drill is slightly out from the drill point on pad ob both axis (X and Y), and this error is random for each point. 

One more thing , that i noticed is, In new version this tutorial doesn't help at all , due to changes in software menus and terms , that were in previous version, so in my opinion tutorials/guides also needed an update regarding the changes in software.

Need help regarding this issue, Please guide to any solution.

Thanks

**Comment by svenhb** [comment]
In principle you  
- move to  first reference point and right click "Add reference point", then move to 
- move to  2nd ref-point and right click "Add reference point" 
- finally press "Start automatic fiducial correction"   
![image](https://user-images.githubusercontent.com/19973251/148974451-014248e2-45b3-48de-b774-dc6326b56676.png)

**Comment by engrjawadulhassan** [comment]
Hello,

What I am doing is:
1.Connect GRBL
2.Load GCODE
3.Open Camera Window
4.Followed your described steps as above

I did the same as you told , but still i am facing the same issue regarding accuracy of new drill point position.
So is there any other step related to this procedure , that i am missing. 

Thanks

**Comment by svenhb** [comment]
I forgot to mentioned: you need the same amount of fiducial coordinates (from 2D-view) and according reference points (from camera view)
