### ISSUE TITLE
zprobe touches block stops then continues down

### ISSUE THREAD

**Issue by tcpd555** [svenhb/GRBL-Plotter#196]
when i use the probing x and y probe works fine, then i do the z probe and it comes down hits block stops for a millisecond and then speeds up down into the block, i have used the probe on UGS and works fine. its just on the z that it does this
![grbl plotter](https://user-images.githubusercontent.com/82959658/116104768-b94f3c80-a67e-11eb-802d-bb3af7e5dad6.png)

**Comment by svenhb** [comment]
Strange... Did you proceed in on go ("Probe Z also" checked). Or first XY and after that "Only Z"?

**Comment by tcpd555** [comment]
i tried it 3 ways, xy with z probe also and bottom left xy, and z only , z probe comes down, touches block very briefly stops then speeds up and drives into block, i have a piece of aluminum rod in spindle now so i dont snap any more tips on bits to test it with

**Comment by tcpd555** [comment]
here is a video of the zprobe 

[](url)https://www.youtube.com/watch?v=ApWSABQG_cE

**Comment by svenhb** [comment]
Wow really bad...
I think the problem is: the "Save distance Z" is smaller than the "Touch plate dimension Z".
After successful Z-Probing, the save distance is 10 mm above the wood, but unfortunatly 11.9 mm below your touch plate...
I should take account of the touch plate dimensions: final position = save distance + touch plate dimension

![image](https://user-images.githubusercontent.com/19973251/116240411-15d85780-a764-11eb-8d04-19a8ca020162.png)

**Comment by tcpd555** [comment]
that was it, i changed save distance to 32 and worked fine, thank you

**Comment by svenhb** [comment]
Very good.
I have thought about it once again: I think it's better to adapt "Save distance" value, when "Touch plate dimension" exceeds this value. 
Because I would expect "Save distance" above workpiece and not above "Touch plate" which I remove after probing.

"Thanks" for finding this issue - too bad you looses some bits.
