### ISSUE TITLE
4-axis function

### ISSUE THREAD

**Issue by lfmmd** [svenhb/GRBL-Plotter#256]
hello i have an idea
My application is to make a curved cutting tool using a 2mm width saw blade that needs to keep the cutting direction and the feeding direction consistent

**Comment by svenhb** [comment]
Hello, I think the tangential function is, what you are looking for: You could also use the Z-axis as the tangential axis, which I've tried here with less success (due to lack of assembly rigidity): https://youtu.be/uMFyTCK8Ggw
![image](https://user-images.githubusercontent.com/19973251/153750535-7415f2fa-d435-4785-ac70-0fd7b2b38d14.png)

**Comment by lfmmd** [comment]
> 您好，我认为切向功能是您要查找的内容：您也可以使用 Z 轴作为切向轴，我在这里尝试过但不太成功（由于缺乏装配刚性）：[https:// youtu.be/uMFyTCK8Ggw](https://youtu.be/uMFyTCK8Ggw) ![图片](https://user-images.githubusercontent.com/19973251/153750535-7415f2fa-d435-4785-ac70-0fd7b2b38d14.png)
Thank you so much for your reply yes this is exactly what I imagined

**Comment by lfmmd** [comment]
> Hello, I think the tangential function is, what you are looking for: You could also use the Z-axis as the tangential axis, which I've tried here with less success (due to lack of assembly rigidity): https://youtu.be/uMFyTCK8Ggw ![image](https://user-images.githubusercontent.com/19973251/153750535-7415f2fa-d435-4785-ac70-0fd7b2b38d14.png)

Thank you so much for your reply yes this is exactly what I imagined
