### ISSUE TITLE
Cutting a circle with a tangential knife did not work properly.

### ISSUE THREAD

**Issue by qulet** [svenhb/GRBL-Plotter#276]
Firmwaere GRBL_LPC
![Kolo](https://user-images.githubusercontent.com/30979927/162043338-430e7b17-d884-4444-955f-e57ecdf73871.png)
The G-code simulation works properly the knife is positioned tangentially during the movement.
G-gode Streaming is not working properly.
The knife travels in a circle without tangential positioning. After the circle is drawn, the A axis begins to move
  For a rectangle, the tangential knife function works fine in Simulation and Streaming.
[lastProcessed_.zip](https://github.com/svenhb/GRBL-Plotter/files/8429540/lastProcessed_.zip)

**Comment by svenhb** [comment]
That is strange, because the code is right: circle and A-axis command are within the same command line and will be processed at the same time. 
I assume something is wrong with your firmware.
![image](https://user-images.githubusercontent.com/19973251/162125053-9567a9af-035d-4765-b3c9-5bee905a4479.png)

**Comment by svenhb** [comment]
If you can't find the problem, you may "avoid G2/G3 commands":
![image](https://user-images.githubusercontent.com/19973251/162127684-2c0b312f-007c-4d34-8eca-5aa0578c26ed.png)

**Comment by qulet** [comment]
Thank you for your answer!
I'll check Avoid G2 / 3 commands.

**Comment by svenhb** [comment]
I hope it is working now
